# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
orbs:
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    environment:
      IMAGE_NAME: ss20matz/nodejs1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
workflows: null
